name: Building Docker BASE armv7 Image

on:
  push:
    branches:
      - v1.46.0-armv7
    tags:
    - "*"

jobs:
  docker-build-base:
    uses: NSerbin/gh-pipelines/.github/workflows/docker-build.yml@main
    with:
      registry: dockerhub
      docker-tag: 20
      dockerfile-path: ./docker/images/n8n-base
      docker-architecture: linux/arm/v7
      repository-name: n8n-base-armv7
      node-version: 20
      linter-fail: true
    secrets: inherit
