name: Building Docker armv7 Image

on:
  push:
    branches:
      - v1.42.1-armv7
    tags:
    - "*"

jobs:
  docker-build-n8n:
    uses: NSerbin/gh-pipelines/.github/workflows/docker-build.yml@main
    with:
      registry: dockerhub
      docker-tag: 1.42.1
      dockerfile-path: ./docker/images/n8n
      docker-architecture: linux/arm/v7
      repository-name: n8n-armv7
    secrets: inherit
